### PR TITLE
Write byte length on OUT request

### LINKED ISSUE #13: usb write does not return correct URB response
Hey!

It looks like when returning a URB response to an IN request, you need to write the length of the bytes written as the urb data length:

image

https://www.kernel.org/doc/html/latest/usb/usbip_protocol.html

Currently, we use the returned response, which in the case of a write is an empty vector. So if a driver etc. writes n bytes and expects n to be returned, it will always see 0.

I have a patch but it is, as per usual, not a small one...

### PR DESCRIPTION
**Pull request by jamesadevine**
* Moves socket logic for reading out data to the place where socket reads and writes are handled. This neatens up the `handle_urb` interface.
* Parse the setup packet and give to handle_urb.
* Fixes #13, where the number of bytes was not set in the URB transfer response `actual_length` field.

### CODE REVIEW

**Comment by jiegec** [comment]
Invited you as a collaborator~

**Comment by jamesadevine** [comment]
Thanks! :smile:

**Comment by jamesadevine** [comment]
@jiegec How do we go about generating a new release for crates.io etc.?

**Comment by jiegec** [comment]
You can login to crates.io, then I can add you to owners.

**Comment by jamesadevine** [comment]
Done!

**Comment by jiegec** [comment]
> Done!

Invited

**Comment by jamesadevine** [comment]
Version 0.6.0 published 🥳

**Pull request merged**
